sonar.projectKey=SidhNor_sketchup-mcp-server
sonar.organization=sidhnor

sonar.sources=src,rakelib
sonar.tests=test
sonar.ruby.coverage.reportPaths=coverage/coverage.json
sonar.exclusions=coverage/**,pkg/**,tmp/**,vendor/**
